name: Build Newton Polygonizer

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    # -------------------- Checkout --------------------
    - name: Checkout repository
      uses: actions/checkout@v3

    # -------------------- Install Dependencies --------------------
    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install cmake -y
        choco install sfml -y
        choco install 7zip -y

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake sfml zip

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libsfml-dev zip

    # -------------------- Configure and Build --------------------
    - name: Configure and Build
      run: |
        set -e
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DSFML_STATIC_LIBRARIES=TRUE -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin ..
        cmake --build . --config Release

    # -------------------- Package --------------------
    - name: Package binaries
      run: |
        set -e
        cd build
        mkdir package

        if [[ "$RUNNER_OS" == "Windows" ]]; then
          cp bin/NewtonPolygon.exe package/
          7z a Newton-Polygonizer-Windows.zip package/*
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          cp bin/NewtonPolygon package/
          zip -r Newton-Polygonizer-macOS.zip package
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          mkdir -p AppDir/usr/bin
          cp bin/NewtonPolygon AppDir/usr/bin/
          tar -czvf Newton-Polygonizer-Linux.tar.gz AppDir
        fi

    # -------------------- Upload to Release --------------------
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/Newton-Polygonizer-Windows.zip
          build/Newton-Polygonizer-macOS.zip
          build/Newton-Polygonizer-Linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
