name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Homebrew
        if: runner.os == 'macOS'
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libsfml-dev zip tar

      - name: Install dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake sfml zip

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DSFML_STATIC_LIBRARIES=ON

      - name: Build
        run: cmake --build build --config Release

      - name: Package executable
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            tar -czvf build/Newton-Polygonizer-Linux.tar.gz -C build NewtonPolygonizer
          else
            zip -j build/Newton-Polygonizer-macOS.zip build/NewtonPolygonizer
          fi

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/Newton-Polygonizer-Linux.tar.gz
            build/Newton-Polygonizer-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
