name: Build Newton Polygonizer for other OS

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Configure and Build
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release

    - name: Package Executable
      run: |
        cd build
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          tar -czvf Newton-Polygonizer-Linux.tar.gz NewtonPolygonizer
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          zip -r Newton-Polygonizer-macOS.zip NewtonPolygonizer
        fi

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload packaged artifacts
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/Newton-Polygonizer-Linux.tar.gz
          build/Newton-Polygonizer-macOS.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
